### ISSUE TITLE
Brightness control does not work

### ISSUE THREAD

**Issue by spupetic** [8none1/idealLED#2]
Hi,

First of all, I would like to thank you for making this integration.

I have successfully set up a device, the color and the effect setting is working, also turning on and off, but the brightness control is not working, neither with simple color, nor with an effect.

**Comment by elessartd** [comment]
i can confirm that. also on my on device i'm unable to set the brightness.

**Comment by 8none1** [comment]
Thanks for the reports. Sounds like a broke something. I’ve packed the lights away now but I’ll look at the code and see if I can spot what I did wrong. If I can’t, I’ll have to get them out and plug them in.

**Comment by 8none1** [comment]
Oh, ok.  I see what I did. I was being lazy.

So, the effects brightness is totally not handled, it's just a fixed number.
The single colours brightness looks like it is hooked up, but I can see that there is a bug.

**Comment by elessartd** [comment]
![Screenshot_20240204_151334](https://github.com/8none1/idealLED/assets/5447223/27d82259-fc1d-4e33-abac-5e44a103ef86)
 i was browsing your code and i've find out the TODO by myself :D As soon as i have time to read HA sdk doc i'll try to send you a merge request.
 
 i've read your blog about how you've bricked your lights... are there any other precautions i have to take when setting brightness? ^^

**Comment by 8none1** [comment]
I've just pushed an untested change which might help the fixed colour brightness:  cd8050a935f0f26d080c97fc5c8fe69132729057
It just scales the RGB colours.  

The brightness for effects I think should be easy to fix, but since I don't have access to the lights at the moment I'm not happy to blindy push something which might actually break.

If you're interested in trying something out:

https://github.com/8none1/idealLED/blob/cd8050a935f0f26d080c97fc5c8fe69132729057/custom_components/ideal_led/idealled.py#L283

You'll need to take the brightness as passed in to that function, convert it from an 8 bit number to a percentage (examples of this elswhere in the code. Multiply by 100 and divide by 255) and the self the self._brightness to the 8 bit number.

**Comment by 8none1** [comment]
> i've read your blog about how you've bricked your lights... are there any other precautions i have to take when setting brightness? ^^

Not that I'm aware of. :cry: 

Worth noting that some of the bytes for brightness seem to be percentages (0-100) and some are 8 bits numbers (0-255).  I am not aware of any problems setting a percentage to more than 100, but I am not at all certain.

**Comment by spupetic** [comment]
I have tried the update, the brightness control is still not working for a solid color and the effects.

**Comment by 8none1** [comment]
Ok, I see what's going on.  Please hold....

**Comment by 8none1** [comment]
... ok, just pushed some more changes.

Brightness for fixed colours definetly works for me now. 
Brifghtness for effects is... odd.  As far as I can tell with the data I have to hand in order to change the brightness of the effect, you actually change the brightness of the colours used.  So that's what I've done.  It kinda works.

Interesting note:  something has changed regarding the notifications from the device.  They never used to work, but suddenly they do.  Could be my new lights have a new firmware version, could be something in HA.  Dunno.  They are currently unused, but I will look at doing something with that data next.

**Comment by spupetic** [comment]
> ... ok, just pushed some more changes.
> 
> Brightness for fixed colours definetly works for me now. Brifghtness for effects is... odd. As far as I can tell with the data I have to hand in order to change the brightness of the effect, you actually change the brightness of the colours used. So that's what I've done. It kinda works.
> 
> Interesting note: something has changed regarding the notifications from the device. They never used to work, but suddenly they do. Could be my new lights have a new firmware version, could be something in HA. Dunno. They are currently unused, but I will look at doing something with that data next.

Thanks for the update, brightness control now works for both a solid color and an effect.

**Comment by elessartd** [comment]
thank you very much 😀
